version: '3'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - app-network
    restart: unless-stopped

  fastapi-service:
    build: ./fastapi-service
    ports:
      - "8000:8000"
    volumes:
      - fastapi_uploads:/app/uploads
      - fastapi_chunks:/app/chunks
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  n8n_data:
  fastapi_uploads:
  fastapi_chunks: